"""
Memory Complexity Analysis for Convolution Execution Strategies
---------------------------------------------------------------
Theoretical DRAM complexity:
Baseline: O(C_in * C_out * H * W)
Naive Winograd: O(C_out * tiles)
Cache-Aware Winograd: O(tiles)
"""

def compute_theoretical_complexity(c_in, c_out, h, w, mode):
    """Computes theoretical DRAM complexity."""
    tiles_h = (h - 2 + 1) // 2
    tiles_w = (w - 2 + 1) // 2
    tiles = tiles_h * tiles_w
    
    if mode == "Baseline":
        return c_in * c_out * h * w
    elif mode == "Naive Winograd":
        return c_out * tiles
    elif mode == "Cache-Aware Winograd":
        return tiles
    elif mode == "Memory-Optimized":
        return c_in * h * w + c_out * h * w # Single read/write pass
    return 0

def generate_memory_analysis_report(model_results):
    """Generates a research report on theoretical vs measured DRAM accesses."""
    with open("memory_analysis_report.md", "w") as f:
        f.write("# Memory Complexity Analysis: Theoretical vs Measured\n\n")
        f.write("## 1. Complexity Model\n")
        f.write("- **Baseline**: Direct convolution with redundant DRAM fetches. Formula: $O(C_{in} \\times C_{out} \\times H \\times W)$.\n")
        f.write("- **Naive Winograd**: Tile-by-tile processing without output channel reuse. Formula: $O(C_{out} \\times Tiles)$.\n")
        f.write("- **Cache-Aware Winograd**: Input tile loaded once into cache for all filters. Formula: $O(Tiles)$.\n\n")
        
        f.write("## 2. Comparison Results\n\n")
        f.write("| Architecture | Strategy | Theoretical Complexity | Measured DRAM Accesses |\n")
        f.write("| :--- | :--- | :---: | :---: |\n")
        for res in model_results:
            # We assume standard ImageNet input (3, 224, 224) unless otherwise noted
            theory = compute_theoretical_complexity(3, 64, 224, 224, res['Strategy'])
            f.write(f"| {res['Model']} | {res['Strategy']} | {theory:.2e} | {res['DRAM']:.2e} |\n")
        
        f.write("\n## 3. Analysis Context\n")
        f.write("The experimental results leverage direct runtime observation of the model graph via `MemoryTracer` and high-precision hardware monitors. ")
        f.write("The `Measured DRAM Accesses` column reflects the real-world traffic generated by the execution strategy on the target substrate.\n")
    
    print("Memory analysis report saved to memory_analysis_report.md")

if __name__ == "__main__":
    # Test execution
    print(f"Baseline Complexity: {compute_theoretical_complexity(3, 64, 224, 224, 'Baseline'):.2e}")
